export const shipmentStatus = {
    DOCUMENTS_PREPARATION: 'DOCUMENTS_PREPARATION',
    CUSTOMS_CLEARANCE: 'CUSTOMS_CLEARANCE',
    PORT_HANDLING: 'PORT_HANDLING',
    DELIVERY: 'DELIVERY',
    COMPLETED: 'COMPLETED'
  };
  
  export const documentTypes = {
    COMMERCIAL_INVOICE: 'COMMERCIAL_INVOICE',
    PACKING_LIST: 'PACKING_LIST',
    BILL_OF_LADING: 'BILL_OF_LADING',
    CERTIFICATE_OF_ORIGIN: 'CERTIFICATE_OF_ORIGIN',
    CUSTOMS_DECLARATION: 'CUSTOMS_DECLARATION'
  };
  
  export const documentStatus = {
    PENDING_VERIFICATION: 'PENDING_VERIFICATION',
    VERIFIED: 'VERIFIED',
    REJECTED: 'REJECTED'
  };
  
  export const customsResponseTypes = {
    CUSTOMS_DECLARATION: 'CUSTOMS_DECLARATION',
    ERROR: 'ERROR',
    PERMIT: 'PERMIT',
    CARGO_RELEASE: 'CARGO_RELEASE'
  };